# Generated by Django 5.1.1 on 2024-12-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_subject_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
