# Generated by Django 5.0.7 on 2024-12-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('adres', models.CharField(max_length=100)),
                ('smtp_server', models.CharField(max_length=100)),
                ('smtp_email', models.CharField(max_length=100)),
                ('smtp_pasword', models.CharField(max_length=100)),
                ('smtp_port', models.CharField(max_length=100)),
                ('youtube', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('icone', models.ImageField(upload_to='images/')),
                ('aboutus', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
